# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infoUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(762, 565)
        self.label_name = QtWidgets.QLabel(Form)
        self.label_name.setGeometry(QtCore.QRect(530, 90, 91, 16))
        self.label_name.setObjectName("label_name")
        self.label_class = QtWidgets.QLabel(Form)
        self.label_class.setGeometry(QtCore.QRect(530, 130, 91, 16))
        self.label_class.setObjectName("label_class")
        self.label_ID = QtWidgets.QLabel(Form)
        self.label_ID.setGeometry(QtCore.QRect(530, 50, 91, 16))
        self.label_ID.setObjectName("label_ID")
        self.bt_changeInfo = QtWidgets.QPushButton(Form)
        self.bt_changeInfo.setGeometry(QtCore.QRect(360, 490, 161, 61))
        self.bt_changeInfo.setObjectName("bt_changeInfo")
        self.bt_collectInfo = QtWidgets.QPushButton(Form)
        self.bt_collectInfo.setGeometry(QtCore.QRect(10, 490, 251, 61))
        self.bt_collectInfo.setObjectName("bt_collectInfo")
        self.label_title = QtWidgets.QLabel(Form)
        self.label_title.setGeometry(QtCore.QRect(170, 10, 251, 16))
        self.label_title.setObjectName("label_title")
        self.bt_checkInfo = QtWidgets.QPushButton(Form)
        self.bt_checkInfo.setGeometry(QtCore.QRect(529, 490, 221, 60))
        self.bt_checkInfo.setObjectName("bt_checkInfo")
        self.label_sex = QtWidgets.QLabel(Form)
        self.label_sex.setGeometry(QtCore.QRect(530, 170, 91, 16))
        self.label_sex.setObjectName("label_sex")
        self.label_birth = QtWidgets.QLabel(Form)
        self.label_birth.setGeometry(QtCore.QRect(530, 210, 91, 16))
        self.label_birth.setObjectName("label_birth")
        self.label_capture = QtWidgets.QLabel(Form)
        self.label_capture.setGeometry(QtCore.QRect(10, 40, 500, 441))
        self.label_capture.setText("")
        self.label_capture.setObjectName("label_capture")
        self.bt_takephoto = QtWidgets.QPushButton(Form)
        self.bt_takephoto.setGeometry(QtCore.QRect(270, 490, 81, 61))
        self.bt_takephoto.setObjectName("bt_takephoto")
        self.lineEdit_ID = QtWidgets.QLineEdit(Form)
        self.lineEdit_ID.setGeometry(QtCore.QRect(630, 40, 121, 31))
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.lineEdit_Name = QtWidgets.QLineEdit(Form)
        self.lineEdit_Name.setGeometry(QtCore.QRect(630, 80, 121, 31))
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.lineEdit_Class = QtWidgets.QLineEdit(Form)
        self.lineEdit_Class.setGeometry(QtCore.QRect(630, 120, 121, 31))
        self.lineEdit_Class.setObjectName("lineEdit_Class")
        self.lineEdit_Sex = QtWidgets.QLineEdit(Form)
        self.lineEdit_Sex.setGeometry(QtCore.QRect(630, 160, 121, 31))
        self.lineEdit_Sex.setObjectName("lineEdit_Sex")
        self.lineEdit_Birth = QtWidgets.QLineEdit(Form)
        self.lineEdit_Birth.setGeometry(QtCore.QRect(630, 200, 121, 31))
        self.lineEdit_Birth.setObjectName("lineEdit_Birth")
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(530, 241, 221, 241))
        self.tableView.setObjectName("tableView")
        self.label_name.raise_()
        self.label_class.raise_()
        self.label_ID.raise_()
        self.bt_collectInfo.raise_()
        self.label_title.raise_()
        self.bt_checkInfo.raise_()
        self.label_sex.raise_()
        self.label_birth.raise_()
        self.bt_changeInfo.raise_()
        self.label_capture.raise_()
        self.bt_takephoto.raise_()
        self.lineEdit_ID.raise_()
        self.lineEdit_Name.raise_()
        self.lineEdit_Class.raise_()
        self.lineEdit_Sex.raise_()
        self.lineEdit_Birth.raise_()
        self.tableView.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_name.setText(_translate("Form", "请输入姓名："))
        self.label_class.setText(_translate("Form", "请输入班级："))
        self.label_ID.setText(_translate("Form", "请输入学号："))
        self.bt_changeInfo.setText(_translate("Form", "修改基本信息"))
        self.bt_collectInfo.setText(_translate("Form", "开始采集"))
        self.label_title.setText(_translate("Form", "人脸识别个人信息采集系统"))
        self.bt_checkInfo.setText(_translate("Form", "查询个人信息（仅输入学号）"))
        self.label_sex.setText(_translate("Form", "请输入性别："))
        self.label_birth.setText(_translate("Form", "请输入生日："))
        self.bt_takephoto.setText(_translate("Form", "拍照"))

