# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 780)
        Form.setMaximumSize(QtCore.QSize(1000, 800))
        self.label_time = QtWidgets.QLabel(Form)
        self.label_time.setGeometry(QtCore.QRect(740, 10, 211, 30))
        self.label_time.setText("")
        self.label_time.setObjectName("label_time")
        self.lcd_1 = QtWidgets.QLCDNumber(Form)
        self.lcd_1.setGeometry(QtCore.QRect(790, 140, 71, 41))
        self.lcd_1.setObjectName("lcd_1")
        self.lcd_2 = QtWidgets.QLCDNumber(Form)
        self.lcd_2.setGeometry(QtCore.QRect(790, 190, 71, 41))
        self.lcd_2.setObjectName("lcd_2")
        self.label_lcdName1 = QtWidgets.QLabel(Form)
        self.label_lcdName1.setGeometry(QtCore.QRect(750, 150, 41, 16))
        self.label_lcdName1.setObjectName("label_lcdName1")
        self.label_lcdName2 = QtWidgets.QLabel(Form)
        self.label_lcdName2.setGeometry(QtCore.QRect(750, 200, 41, 16))
        self.label_lcdName2.setObjectName("label_lcdName2")
        self.label_listName1 = QtWidgets.QLabel(Form)
        self.label_listName1.setGeometry(QtCore.QRect(750, 320, 31, 16))
        self.label_listName1.setObjectName("label_listName1")
        self.label_listName2 = QtWidgets.QLabel(Form)
        self.label_listName2.setGeometry(QtCore.QRect(750, 470, 41, 16))
        self.label_listName2.setObjectName("label_listName2")
        self.bt_view = QtWidgets.QPushButton(Form)
        self.bt_view.setGeometry(QtCore.QRect(750, 630, 201, 61))
        self.bt_view.setObjectName("bt_view")
        self.bt_leave = QtWidgets.QPushButton(Form)
        self.bt_leave.setGeometry(QtCore.QRect(850, 240, 101, 31))
        self.bt_leave.setObjectName("bt_leave")
        self.bt_exit = QtWidgets.QPushButton(Form)
        self.bt_exit.setGeometry(QtCore.QRect(750, 700, 201, 71))
        self.bt_exit.setObjectName("bt_exit")
        self.label_class = QtWidgets.QLabel(Form)
        self.label_class.setGeometry(QtCore.QRect(750, 60, 71, 16))
        self.label_class.setObjectName("label_class")
        self.label_location = QtWidgets.QLabel(Form)
        self.label_location.setGeometry(QtCore.QRect(750, 100, 72, 15))
        self.label_location.setObjectName("label_location")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(820, 50, 131, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(820, 90, 131, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.bt_check = QtWidgets.QPushButton(Form)
        self.bt_check.setGeometry(QtCore.QRect(870, 140, 81, 91))
        self.bt_check.setObjectName("bt_check")
        self.bt_gathering = QtWidgets.QPushButton(Form)
        self.bt_gathering.setGeometry(QtCore.QRect(10, 700, 181, 71))
        self.bt_gathering.setObjectName("bt_gathering")
        self.bt_startCheck = QtWidgets.QPushButton(Form)
        self.bt_startCheck.setGeometry(QtCore.QRect(440, 700, 171, 71))
        self.bt_startCheck.setObjectName("bt_startCheck")
        self.bt_blinks = QtWidgets.QPushButton(Form)
        self.bt_blinks.setGeometry(QtCore.QRect(620, 700, 111, 71))
        self.bt_blinks.setObjectName("bt_blinks")
        self.label_title = QtWidgets.QLabel(Form)
        self.label_title.setGeometry(QtCore.QRect(160, 20, 400, 40))
        self.label_title.setText("")
        self.label_title.setObjectName("label_title")
        self.bt_openCamera = QtWidgets.QPushButton(Form)
        self.bt_openCamera.setGeometry(QtCore.QRect(330, 700, 101, 71))
        self.bt_openCamera.setObjectName("bt_openCamera")
        self.label_camera = QtWidgets.QLabel(Form)
        self.label_camera.setGeometry(QtCore.QRect(20, 80, 700, 600))
        self.label_camera.setText("")
        self.label_camera.setObjectName("label_camera")
        self.label_logo = QtWidgets.QLabel(Form)
        self.label_logo.setGeometry(QtCore.QRect(20, 70, 700, 600))
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        self.bt_generator = QtWidgets.QPushButton(Form)
        self.bt_generator.setGeometry(QtCore.QRect(200, 700, 111, 71))
        self.bt_generator.setObjectName("bt_generator")
        self.tableView_escape = QtWidgets.QTableView(Form)
        self.tableView_escape.setGeometry(QtCore.QRect(750, 490, 201, 131))
        self.tableView_escape.setObjectName("tableView_escape")
        self.tableView_late = QtWidgets.QTableView(Form)
        self.tableView_late.setGeometry(QtCore.QRect(750, 340, 201, 121))
        self.tableView_late.setObjectName("tableView_late")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(750, 240, 91, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(750, 280, 91, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.bt_Supplement = QtWidgets.QPushButton(Form)
        self.bt_Supplement.setGeometry(QtCore.QRect(850, 280, 101, 31))
        self.bt_Supplement.setObjectName("bt_Supplement")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_lcdName1.setText(_translate("Form", "应到"))
        self.label_lcdName2.setText(_translate("Form", "实到"))
        self.label_listName1.setText(_translate("Form", "未到"))
        self.label_listName2.setText(_translate("Form", "迟到"))
        self.bt_view.setText(_translate("Form", "查看结果"))
        self.bt_leave.setText(_translate("Form", "请假登记"))
        self.bt_exit.setText(_translate("Form", "退出系统"))
        self.label_class.setText(_translate("Form", "考勤班级"))
        self.label_location.setText(_translate("Form", "考勤地点"))
        self.comboBox.setItemText(0, _translate("Form", "2020001"))
        self.comboBox.setItemText(1, _translate("Form", "2020002"))
        self.comboBox_2.setItemText(0, _translate("Form", "01J"))
        self.comboBox_2.setItemText(1, _translate("Form", "02J"))
        self.comboBox_2.setItemText(2, _translate("Form", "10J"))
        self.comboBox_2.setItemText(3, _translate("Form", "11J"))
        self.bt_check.setText(_translate("Form", "查询"))
        self.bt_gathering.setText(_translate("Form", "信息采集"))
        self.bt_startCheck.setText(_translate("Form", "开始考勤"))
        self.bt_blinks.setText(_translate("Form", "活体检测"))
        self.bt_openCamera.setText(_translate("Form", "打开相机"))
        self.bt_generator.setText(_translate("Form", "更新人脸库"))
        self.bt_Supplement.setText(_translate("Form", "漏签补签"))

